backend:
  name: git-gateway
  branch: master

media_folder: src/pages/assets
public_folder: ../../assets
public_folder_relative: true
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog/entries"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Path", name: "path", widget: "string", required: false}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - label: "Theme"
        name: "theme"
        widget: "select"
        options:
          - { label: "Light", value: "light" }
          - { label: "Dark", value: "dark" }
      - {label: "Body", name: "body", widget: "markdown", required: false} 
      - {label: "Tags", name: "tags", widget: "relation" , collection: "tags", searchFields: "title", valueField: "slug", required: false}

  - name: "tags"
    label: "Tags"
    folder: "src/pages/blog/tags"
    slug: "{{slug}}"
    create : true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-tag"}
      - {label: "Path", name: "path", widget: "string", required: false}

  - name: "projects"
    label: "Projects"
    folder: "src/pages/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "project-entry"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false} 
      - {label: "Featured Image", name: "hero", widget: "image", required: false}
      - label: "Theme"
        name: "theme"
        widget: "select"
        options:
          - { label: "Light", value: "light" }
          - { label: "Dark", value: "dark" }
      - {label: "Body", name: "body", widget: "markdown", required: false}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/about.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/about"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/blog/blog.md"
        label: "Blog"
        name: "blog"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/blog"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
   
  - name: "config"
    label: "Configuration"
    files:
      - file: "src/pages/navigation.md"
        label: "Navigation Bar"
        name: "navbar"
        fields:
          - {label: "Content Type", name: "contentType", widget: "hidden", default: "navigationStructure"}
          - name: links
            label: Links
            widget: list
            fields:
              - {label: Label, name: label, widget: string}
              - {label: URL, name: url, widget: string}

  